name: vayu_drishti
description: "VayuDrishti - ISRO Satellite Air Quality Monitor App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Maps & Location
  google_maps_flutter: ^2.9.0
  location: ^8.0.1
  geolocator: ^14.0.2
  
  # Charts & Visualization
  fl_chart: ^1.1.0
  
  # Utils
  shared_preferences: ^2.3.2
  intl: ^0.20.2
  
  # UI Components
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
